exports.CitizenController = require("./CitizenController")
exports.ChallanController = require("./ChallanController")
exports.WardenController = require("./WardenController")
exports.VehicleController = require("./VehicleController")
exports.AuthController = require("./AuthController")
exports.VoilationController = require("./VoilationController")