exports.Citizen = require("./CitizenModel")
exports.Warden = require("./WardenModel")
exports.Challan = require("./ChallanModel")
exports.Voilation = require("./VoilationModel")
exports.WardenImage = require("./ImageModel")
exports.Admn = require("./AdminModel")
exports.WardenApproval = require("./WardenApprovalModel")