export { default as Login } from "./Login"
export { default as SignUp } from "./SignUp"
export { default as CreateNewPassword } from "./CreateNewPassword"
export { default as ForgotPassword } from "./ForgotPassword"
export { default as VerificationCode } from "./VerificationCode"
export { default as UploadPhoto } from "./UploadPhoto"
export { default as UploadPhotoFinal } from "./UploadPhotoFinal"